services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: tasks
      POSTGRES_PASSWORD: taskspass
      POSTGRES_DB: tasksdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      POSTGRES_USER: tasks
      POSTGRES_PASSWORD: taskspass
      POSTGRES_DB: tasksdb
      POSTGRES_HOST: postgres

volumes:
  postgres_data:
